---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if connection still works
      ansible.builtin.ping:

    - name: Use mongosh
      ansible.builtin.shell: mongosh --eval "db.version()"
      register: mongosh_result
      changed_when: false
      failed_when: "'6.0.' not in mongosh_result.stdout"
